# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Run all lint checks
name: lint
on: [push, pull_request]

jobs:
  ######################
  # Clang-Format Check #
  ######################
  # Check C/C++ files for correct formatting.
  clangfmt:
    name: C/C++ Sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Changed C sources
      id: src_files
      run: |
        src_files=$(for f in ${{ steps.files.outputs.added_modified }}; do echo $f | grep '.*/.*\.\(c\|cpp\|h\)$' ||:; done)
        echo "::set-output name=src_files::$src_files\n"
        echo "Changed: ${{ steps.files.outputs.added_modified }}"
        echo "Cxx changed: $src_files"
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        clangFormatVersion: 12
        extensions: 'h,cpp,c'
        source: ${{ steps.files.outputs.added_modified }}
